name: Build Image

on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: "Image"
        required: true
        default: "chromium"
        options: ["base", "chromium", "firefox"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Getting browserless
        uses: actions/checkout@v4
        with:
          repository: "browserless/browserless"
          ref: "b0cc4c73d299bc7a7e5c6f7c1ebe19ac62818253"
          fetch-depth: 0
          submodules: recursive
          path: ./browserless

      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          path: ./browserless-arm

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Base
        if: ${{ github.event.inputs.type == 'base' }}
        uses: docker/build-push-action@v6
        with:
          context: ./browserless
          file: ./browserless-arm/Dockerfile.base
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/browserless-arm-base:latest
          platforms: linux/arm/v7

      - name: Build Chromium
        if: ${{ github.event.inputs.type == 'chromium' }}
        uses: docker/build-push-action@v6
        with:
          context: ./browserless
          file: ./browserless-arm/Dockerfile.chromium
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/browserless-arm-chromium:latest
          platforms: linux/arm/v7
          build-args: |
            VERSION=latest

      - name: Build Firefox
        if: ${{ github.event.inputs.type == 'firefox' }}
        uses: docker/build-push-action@v6
        with:
          context: ./browserless
          file: ./browserless-arm/Dockerfile.firefox
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/browserless-arm-firefox:latest
          platforms: linux/arm/v7
          build-args: |
            VERSION=latest
